### ISSUE TITLE
User (admin) login & admin home

### ISSUE THREAD

**Issue by jasoncrawford** [objectivists/translations#1]
## Goals

We need user login for the admin part of the UI where we will edit the data.

## Requirements

This is done when:

- [ ] There is a User model in the system with some form of authentication (email & password is fine)
- [ ] There is a login page at `/login`
- [ ] Logging in takes you to an admin page at `/admin`. Right now this page doesn't have to have anything on it; in the future it will have links to admin pages for all the data in the system.
- [ ] Hitting `/admin` without being logged in redirects you to `/login`.
- [ ] If we're doing email/password, there should really be a reset-password flow as well.

Open questions:

* What's the best way to add and manage admin users? Should that be part of the admin UI itself? We don't want to let just anyone sign up. Alternately, we could just use the Rails console to manage users—we won't be adding admins very often.

**Comment by jasoncrawford** [comment]
Open question, should we use a gem like Devise for this?

**Comment by jasoncrawford** [comment]
Decided to punt on this for now. We're going to start building the models and admin/scaffolding without auth or with HTTP basic auth. Will come back later and decide whether we want a full User scheme.

**Comment by dominicbertolino** [comment]
Looked more into this and I think I'm going to go with a homegrown solution unless there are objections. Rails 3.1 added better support for authentication and it looks dead simple to get up and running ([here is](http://railscasts.com/episodes/270-authentication-in-rails-3-1?autoplay=true) a rails cast showing it). Also, Devise seems to be much more than we'd need.

As far as the best way to add and manage admin users, I think having the sign-up page be admin-only then adding an initial user through the rails console would work ok.

**Comment by jasoncrawford** [comment]
Nice, they have bcrypt support built in. Sure, sounds good.
