### ISSUE TITLE
Translation model & admin UI

### ISSUE THREAD

**Issue by jasoncrawford** [objectivists/translations#4]
## Translation model

The Translation model:

* belongs to Book (#2)
* belongs to Language (#3)

It has:

* title: the title of the book in that language (e.g., “El Manantial” or “Noi Vivi”)
* cover image (URL)
* publisher
* ISBN
* ASIN (Amazon ID)
* translator name

## Requirements

This is done when:

- [ ] The Translation model exists
- [ ] There's a link on the admin page (#1) to `/admin/translations`
- [ ] There is admin UI (scaffolding) at `/admin/translations` to list, create, show, and edit (and delete?) translations.
- [ ] The admin UI all requires authentication as an (admin) user.

**Comment by dominicbertolino** [comment]
For books, the Amazon ASIN is the 10 digit ISBN. Since book listings typically refer to it as the ISBN,  I'm going to just have ISBN_10 and ISBN_13 fields as I think this will be clearer.

I think both are necessarily to include as optional fields as the ISBN_13 was introduced in 2007 and it doesn't seem like a given book is required to have both.

**Comment by jasoncrawford** [comment]
Oh, interesting. OK, that makes sense.

**Comment by dominicbertolino** [comment]
It looks like we'll want to use a library to handle uploading cover images. After looking into image uploader gems a bit, I think going with [CarrierWave](https://github.com/carrierwaveuploader/carrierwave) makes sense. It's well supported and commonly recommended. It has more features than we'd ever use but seems to handle the simple use cases nicely. The major alternative I found was [Paperclip](https://github.com/thoughtbot/paperclip) which is more stripped down (which for our project would be fine) but lacks some of the modularity of CarrierWave by being tightly coupled with ActiveRecord. 

I'm going to start going down the path of CarrierWave for now but let me know if there are any other suggestions.

**Comment by jasoncrawford** [comment]
Good point, we will probably want to host our own copies of images. I assume we'll just set up S3 for this?

**Comment by dominicbertolino** [comment]
I haven't looked at other options but S3 is cheap (it would be free for the first year and cents per month afterwards) and easily integrates with either uploader gem.
