### ISSUE TITLE
Decide on UI framework

### ISSUE THREAD

**Issue by jasoncrawford** [objectivists/translations#8]
* Bootstrap? What should we use?
* Related, should we use something like Sass?

Ideally we build the UI in a way that is mobile-friendly (responsive) and SEO-friendly.

**Comment by jasoncrawford** [comment]
Tentative decisions:

* Use Bootstrap
* Maybe use Sass/SCSS (if not, stick with plain CSS)
* Server-side HTML rendering for now

**Comment by timcheadle** [comment]
Bootstrap + SCSS is probably the right way to go. It's well documented, relatively easy to use and customize, and has good Rails support.

Trust me you don't want to write raw CSS if you can use SCSS. Also, make sure you use SCSS, not Sass. Sass syntax is awful.

**Comment by jasoncrawford** [comment]
OK, let's call Bootstrap + SCSS a decision then. Thanks Tim!
